<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27218" started-at="2018-04-16T05:45:47Z" finished-at="2018-04-16T05:46:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="27218" started-at="2018-04-16T05:45:47Z" finished-at="2018-04-16T05:46:14Z">
      <class name="com.tests.testcases">
        <test-method status="PASS" signature="login_Test_Case_02()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="login_Test_Case_02" duration-ms="27039" started-at="2018-04-16T11:15:47Z" finished-at="2018-04-16T11:16:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test_Case_02 -->
        <test-method status="PASS" signature="login_Test_Case_03()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="login_Test_Case_03" duration-ms="26932" started-at="2018-04-16T11:15:47Z" finished-at="2018-04-16T11:16:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test_Case_03 -->
        <test-method status="FAIL" signature="login_Test_Case_04()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="login_Test_Case_04" duration-ms="1293" started-at="2018-04-16T11:15:47Z" finished-at="2018-04-16T11:15:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.tests.testcases.login_Test_Case_04(testcases.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test_Case_04 -->
        <test-method status="FAIL" signature="login_Test_Case_05()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="login_Test_Case_05" duration-ms="1290" started-at="2018-04-16T11:15:47Z" finished-at="2018-04-16T11:15:48Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.tests.testcases.login_Test_Case_05(testcases.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test_Case_05 -->
        <test-method status="PASS" signature="login_Test_Case_01()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="login_Test_Case_01" duration-ms="27134" started-at="2018-04-16T11:15:47Z" finished-at="2018-04-16T11:16:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_Test_Case_01 -->
        <test-method status="PASS" signature="flush_test()[pri:0, instance:com.tests.testcases@1e4a7dd4]" name="flush_test" is-config="true" duration-ms="53" started-at="2018-04-16T11:16:14Z" finished-at="2018-04-16T11:16:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush_test -->
      </class> <!-- com.tests.testcases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
